apiVersion: v1
kind: Secret
metadata:
  name: {{ template "payments.fullname" . }}
  labels:
    app: {{ template "payments.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  mongo-uri: {{ .Values.mongoURI }}

