apiVersion: v1
kind: Secret
metadata:
  name: {{ template "runtime-environment-manager.fullname" . }}-registry
  labels:
    app: {{ template "runtime-environment-manager.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service  | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson .Values.dockerconfigjson | b64enc | quote }}
