apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailer.fullname" . }}
  labels:
    app: {{ template "mailer.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  sendgrid-key: {{ .Values.sendgridKey }}

