apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cf-cfapi
  namespace: codefresh-dev
spec:
  host: g.apps-os-t1.cf-cd.com
  path: /api
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: cf-cfapi
    weight: 100
  # wildcardPolicy: None