apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cf-cfui
  namespace: codefresh-dev
spec:
  host: codefresh-dev.v12.np01.ocp.six-group.net
  # path: /
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: cf-cfui
  #  weight: 0
  # wildcardPolicy: None