args: null
image: bitnami/redis:4.0.9-r0
imagePullPolicy: IfNotPresent
metrics:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  enabled: false
  image: oliver006/redis_exporter
  imagePullPolicy: IfNotPresent
  imageTag: v0.11
  resources: {}
networkPolicy:
  allowExternal: true
  enabled: false
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  path: /bitnami
  size: 8Gi
  subPath: ""
podAnnotations: {}
podLabels: {}
redisDisableCommands: FLUSHDB,FLUSHALL
redisExtraFlags: null
resources:
  requests:
    cpu: 100m
    memory: 256Mi
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
service:
  annotations: {}
  loadBalancerIP: null
serviceType: ClusterIP
tolerations: []
usePassword: true
