image: bitnami/redis:3.2.9-r2
imagePullPolicy: IfNotPresent
metrics:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  enabled: false
  image: oliver006/redis_exporter
  imagePullPolicy: IfNotPresent
  imageTag: v0.11
  resources: {}
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 8Gi
resources:
  requests:
    cpu: 100m
    memory: 256Mi
tolerations: []
usePassword: true
