{{- if $.Values.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
spec:
  storageClassName: nfs-six-backup-none
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.mongodb.persistentVolumeClaimSize }}
{{- end }}
