apiVersion: v1
kind: Secret
metadata:
  name: {{ template "context-manager.fullname" . }}
  labels:
    app: {{ template "context-manager.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  mongo-uri: {{ coalesce .Values.mongoURI (include "calculateMongoURI" (dict "dbName" .Values.global.contextManagerService "mongoURI" .Values.global.mongoURI)) }}
  safe-secret: {{ .Values.safeSecret | quote }}

