apiVersion: v1
description: Ingress controller and default http backend.
icon: https://sysdig.com/wp-content/uploads/2017/05/Kubernetes_Nginx_1.jpg
keywords:
- docker
- ingress controller
- http backend
maintainers:
- email: admin@codefresh.io
  name: Codefresh
name: ingress
sources:
- https://github.com/kubernetes/ingress
version: 0.1.8
