apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cf-broadcaster.fullname" . }}
  labels:
    app: {{ template "cf-broadcaster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  newrelic-license-key: {{ .Values.newrelicLicenseKey | quote }}