{{- if .Values.ingress.enabled }}
{{- if .Values.webTLS }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cfui.fullname" . }}-tls
  labels:
    app: {{ template "cfui.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webTLS.cert | b64enc | quote }}
  tls.key: {{ .Values.webTLS.key | b64enc | quote }}
{{- end }}
{{- end }}
