apiVersion: v1
kind: Secret
metadata:
    name: {{ template "cfapi.fullname" . }}
    labels:
      app: {{ template "cfapi.fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
    # GitHub secrets
    github-client-id: {{ default "" .Values.global.githubClientID | quote }}
    github-client-secret: {{ default "" .Values.global.githubClientSecret | quote }}
    github-internal-token: {{ default "" .Values.global.githubInternalToken | quote }}

    gcs-private-key: {{ default "" .Values.gcsPrivateKey | quote }}

    # GitLab secrets
    gitlab-client-id: {{ default "" .Values.global.gitlabClientID | quote }}
    gitlab-client-secret: {{ default "" .Values.global.gitlabClientSecret | quote }}

    # Bitbucket context secrets
    bitbucket-client-id: {{ default "" .Values.global.bitbucketClientID | quote }}
    bitbucket-client-secret: {{ default "" .Values.global.bitbucketClientSecret | quote }}

  # Bitbucket login secrets
    bitbucket-login-client-id: {{ default "" .Values.global.bitbucketLoginClientID | quote }}
    bitbucket-login-client-secret: {{ default "" .Values.global.bitbucketLoginClientSecret | quote }}

    # ssh secrets
    {{- if .Values.sshMasterSecret }}
    sshMasterSecret: |
      {{ .Values.sshMasterSecret }}
    {{- end }}

    # AWS secrets
    {{- if .Values.awsCredentials }}
    aws-credentials: |
      [default]
        aws_access_key_id={{ .Values.awsCredentials.awsAccessKeyId }}
        aws_secret_access_key={{ .Values.awsCredentials.awsSecretAccessKey }}
    {{- end }}

    # AWS secrets
    {{- if .Values.gceCredentials }}
    gce-credentials: |
      {{ .Values.gceCredentials }}
    {{- end }}

    # AWS secrets
    {{- if .Values.azureCredentials }}
    azure-credentials: |
      {{ .Values.azureCredentials }}
    {{- end }}
    {{- if or .Values.global.onprem .Values.global.dynamic }}
    mongo-uri: {{ include "calculateMongoURI" (dict "dbName" .Values.global.mongodbDatabase "mongoURI" .Values.global.mongoURI) }}
    {{- else }}
    mongo-uri: {{ default "" .Values.global.mongoURI | quote }}
    {{- end }}
